In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error

In [8]:
for root, dirs,files in os.walk('results\\test'):
    for file in files:
        if file.endswith('.csv.csv'):
            oldpath = os.path.join(root, file)
            newpath = os.path.join(root, file.replace('.csv.csv', '.csv'))
            os.rename(oldpath, newpath)

In [52]:
df = pd.read_csv('results\\test\\RidgewithClose\\data_daily_^DJI.csv')
df = df.reset_index()[['actual', 'predict']]

# correct = 0
# for i in range(1, len(df)):
#     correct += (df.actual.iloc[i]<df.actual.iloc[i-1]) == (df.predict.iloc[i]<df.predict.iloc[i-1])
    
# correct/len(df)

def direc_accuracy(y_actual, y_predict):
    correct = 0
    for i in range(1, len(y_actual)):
        correct += (y_predict[i]<y_predict[i-1]) == (y_actual[i]<y_actual[i-1])
        
    return correct/len(y_actual)

print(direc_accuracy(df.actual, df.predict))

0.5074626865671642

In [63]:
path = "results\\test"

results_df = pd.DataFrame(columns=['model','data', 'ticker', 'timeframe', 'datasize', 'MAPE', 'DirecAccuracy', 'MSE'])
for model in os.listdir(path):
    files = os.listdir(os.path.join(path, model))
    for file in files:
        if not file.endswith('.csv'): continue
        
        data = ''
        if file.startswith('data'):
            data, timeframe, ticker = 'data', file.split('_')[1], file.split('_')[2][:-4]
        elif file.startswith('gbm_nl'):
            data, timeframe, ticker = 'gbm_nl', file.split('_')[2], file.split('_')[3][:-4]
        elif file.startswith('gbm'):
            data, timeframe, ticker = 'gbm', file.split('_')[1], file.split('_')[2][:-4]
        elif file.startswith('jump_diffusion'):
            data, timeframe, ticker = 'jump_diffusion', file.split('_')[2], file.split('_')[3][:-4]
            
        df = pd.read_csv(os.path.join(path, model, file))
        
        size = len(df)
        MAPE = mean_absolute_percentage_error(df.actual, df.predict)
        DirecAccuracy = direc_accuracy(df.actual, df.predict)
        MSE = mean_squared_error(df.actual, df.predict)
        
        results_df.loc[len(results_df)] = [model, data, ticker, timeframe, size, MAPE, DirecAccuracy, MSE]

results_df

,model,data,ticker,timeframe,datasize,MAPE,DirecAccuracy,MSE
0,ElasticNetTunedwithClose,data,AAPL,daily,67,0.019409,0.507463,31.919313
1,ElasticNetTunedwithClose,data,BIRET.BO,daily,68,0.006353,0.382353,6.929782
2,ElasticNetTunedwithClose,data,DLF.NS,daily,68,0.017832,0.455882,313.745846
3,ElasticNetTunedwithClose,data,EMBASSY.BO,daily,68,0.008332,0.426471,15.037819
4,ElasticNetTunedwithClose,data,GC=F,daily,69,0.013891,0.347826,3354.139057
...,...,...,...,...,...,...,...,...
3595,XGBwithIndicators,jump_diffusion,OBEROIRLTY.NS,hourly,56,0.006980,0.571429,185.386196
3596,XGBwithIndicators,jump_diffusion,^DJI,hourly,54,0.002319,0.611111,11415.490740
3597,XGBwithIndicators,jump_diffusion,^GSPC,hourly,54,0.007824,0.425926,4824.424424
3598,XGBwithIndicators,jump_diffusion,^N225,hourly,55,0.005715,0.509091,34190.858664
3599,XGBwithIndicators,jump_diffusion,^NSEI,hourly,56,0.002896,0.410714,13201.824188

In [67]:
results_df.describe()

          datasize         MAPE  DirecAccuracy           MSE
count  3600.000000  3600.000000    3600.000000  3.600000e+03
mean     87.111111     0.048462       0.493288  6.964343e+05
std      58.159116     0.257429       0.059174  8.809626e+06
min      54.000000     0.001056       0.267857  1.697262e-05
25%      56.000000     0.006246       0.455882  8.861430e+00
50%      67.000000     0.014477       0.494681  2.238474e+02
75%      68.000000     0.032761       0.531915  6.565098e+03
max     315.000000     9.895334       0.678571  2.659644e+08

In [89]:
wmape_df = pd.DataFrame(columns=['model', 'data', 'gbm', 'gbm_nl', 'jump_diffusion'])
for model in results_df.model.unique():
    mapes = []
    for data in ['data', 'gbm', 'gbm_nl', 'jump_diffusion']:
        model_results = results_df[(results_df.model == model) & (results_df.data == data)]
        weighted_MAPE = (model_results.datasize * model_results.MAPE).sum() / model_results.datasize.sum()
        mapes += [weighted_MAPE*100]
    wmape_df.loc[len(wmape_df)] = [model, *mapes]

wmape_df

                       model       data        gbm     gbm_nl  jump_diffusion
0   ElasticNetTunedwithClose   0.804677   0.949164   1.212779        0.945303
1        ElasticNetwithClose  18.968168  19.324422  31.228683       14.863536
2   ElasticNetwithIndicators  18.968168  19.324422  31.228683       14.863536
3          KNNTunedwithClose   3.075851   3.261144   2.696319        2.923563
4               KNNwithClose   3.059228   3.153965   2.715098        2.894640
5          KNNwithIndicators   3.059228   3.153965   2.715098        2.894640
6         LGBMTunedwithClose   2.110091   2.224374   1.766412        1.814083
7              LGBMwithClose   2.081230   2.443882   1.789747        1.866944
8         LGBMwithIndicators   2.081230   2.443882   1.789747        1.866944
9              LSTMwithClose   7.786107   8.204340  17.936517        6.826800
10         RFRTunedwithClose   1.833183   2.102204   1.629807        1.723778
11              RFRwithClose   1.854544   2.046018   1.640930        1.732324
12         RFRwithIndicators   1.938321   2.095573   1.694292        1.791804
13       RidgeTunedwithClose   0.673495   0.878292   0.882611        0.897524
14            RidgewithClose   0.678844   0.884043   0.879655        0.912733
15       RidgewithIndicators   0.674222   0.879969   0.883238        0.909069
16        SGDRTunedwithClose   1.375274   2.822060   4.678605        1.603563
17             SGDRwithClose   1.163792   1.345364   1.519621        1.558303
18        SGDRwithIndicators   0.879868   1.043418   1.445802        1.099874
19              SVMwithClose   2.280183   3.677080   2.631116        2.498505
20         SVMwithIndicators   3.150611   3.961766   3.132207        2.778082
21         SVRTunedwithClose   4.964643   7.871832  26.997583        4.566254
22         XGBTunedwithClose   2.885926   2.876031   5.220720        2.149068
23              XGBwithClose   2.193457   2.361958   2.024109        1.874305
24         XGBwithIndicators   2.193457   2.361958   2.024109        1.874305

In [90]:
direcacc_df = pd.DataFrame(columns=['model', 'data', 'gbm', 'gbm_nl', 'jump_diffusion'])
for model in results_df.model.unique():
    das = []
    for data in ['data', 'gbm', 'gbm_nl', 'jump_diffusion']:
        model_results = results_df[(results_df.model == model) & (results_df.data == data)]
        weighted_DA = (model_results.datasize * model_results.DirecAccuracy).sum() / model_results.datasize.sum()
        das += [weighted_DA]
    direcacc_df.loc[len(direcacc_df)] = [model, *das]

direcacc_df

                       model      data       gbm    gbm_nl  jump_diffusion
0   ElasticNetTunedwithClose  0.487245  0.483099  0.500000        0.492666
1        ElasticNetwithClose  0.510523  0.487245  0.493622        0.486607
2   ElasticNetwithIndicators  0.510523  0.487245  0.493622        0.486607
3          KNNTunedwithClose  0.517857  0.482462  0.494260        0.508291
4               KNNwithClose  0.488520  0.478954  0.498087        0.508929
5          KNNwithIndicators  0.488520  0.478954  0.498087        0.508929
6         LGBMTunedwithClose  0.506696  0.500638  0.493941        0.492666
7              LGBMwithClose  0.516901  0.502232  0.494260        0.500638
8         LGBMwithIndicators  0.516901  0.502232  0.494260        0.500638
9              LSTMwithClose  0.492347  0.482781  0.493304        0.487564
10         RFRTunedwithClose  0.501594  0.491071  0.497768        0.497130
11              RFRwithClose  0.501276  0.490434  0.506696        0.496173
12         RFRwithIndicators  0.485651  0.487564  0.497449        0.502870
13       RidgeTunedwithClose  0.480548  0.481186  0.500638        0.488202
14            RidgewithClose  0.482462  0.478954  0.503508        0.492666
15       RidgewithIndicators  0.484694  0.476084  0.503508        0.489477
16        SGDRTunedwithClose  0.496173  0.482143  0.499681        0.493941
17             SGDRwithClose  0.507653  0.481186  0.484375        0.508291
18        SGDRwithIndicators  0.491390  0.490753  0.496173        0.485332
19              SVMwithClose  0.493941  0.487883  0.498724        0.496492
20         SVMwithIndicators  0.486926  0.489158  0.501913        0.487564
21         SVRTunedwithClose  0.502870  0.487245  0.486926        0.487245
22         XGBTunedwithClose  0.512436  0.486288  0.497449        0.492666
23              XGBwithClose  0.513393  0.487245  0.503827        0.495855
24         XGBwithIndicators  0.513393  0.487245  0.503827        0.495855