In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from utils.ticker_data import get_stock_data, windowed_dfs

In [2]:
df = pd.read_csv("data/daily/^GSPC.csv")
df.head()

,Date,Open,High,Low,Close,Volume,logReturns
0,2000-01-04,1455.219971,1455.219971,1397.430054,1399.420044,1009000000,-0.039099
1,2000-01-05,1399.420044,1413.270020,1377.680054,1402.109985,1085500000,0.001920
2,2000-01-06,1402.109985,1411.900024,1392.099976,1403.449951,1092300000,0.000955
3,2000-01-07,1403.449951,1441.469971,1400.729980,1441.469971,1225200000,0.026730
4,2000-01-10,1441.469971,1464.359985,1441.469971,1457.599976,1064800000,0.011128

In [41]:
column_data = {"Close" : 5, "High": 3, "Volume" : 2}
target = 'Close'
max_horizon = max(column_data.values())
target_row = df[target].iloc[max_horizon:].values

full_windowed = np.array([])
for col in column_data:
    df_col = df[col]
    windowed_col = np.array([df_col.iloc[i-column_data[col]:i].values for i in range(max_horizon, len(df_col))])
    
    if len(full_windowed) == 0:
        full_windowed = windowed_col
    else:
        full_windowed = np.concatenate((full_windowed, windowed_col), axis=1)

column_names = [f"{col.lower()}-{i}" for col in column_data for i in range(column_data[col], 0, -1) ]
windowed_df= pd.DataFrame(full_windowed, columns=column_names)
windowed_df

,close-5,close-4,close-3,close-2,close-1,high-3,high-2,high-1,volume-2,volume-1
0,1399.420044,1402.109985,1403.449951,1441.469971,1457.599976,1411.900024,1441.469971,1464.359985,1.225200e+09,1.064800e+09
1,1402.109985,1403.449951,1441.469971,1457.599976,1438.560059,1441.469971,1464.359985,1458.660034,1.064800e+09,1.014000e+09
2,1403.449951,1441.469971,1457.599976,1438.560059,1432.250000,1464.359985,1458.660034,1442.599976,1.014000e+09,9.746000e+08
3,1441.469971,1457.599976,1438.560059,1432.250000,1449.680054,1458.660034,1442.599976,1454.199951,9.746000e+08,1.030400e+09
4,1457.599976,1438.560059,1432.250000,1449.680054,1465.150024,1442.599976,1454.199951,1473.000000,1.030400e+09,1.085900e+09
...,...,...,...,...,...,...,...,...,...,...
6408,6173.069824,6204.950195,6198.009766,6227.419922,6279.350098,6210.779785,6227.600098,6284.649902,5.645710e+09,3.378110e+09
6409,6204.950195,6198.009766,6227.419922,6279.350098,6229.979980,6227.600098,6284.649902,6262.069824,3.378110e+09,5.236740e+09
6410,6198.009766,6227.419922,6279.350098,6229.979980,6225.520020,6284.649902,6262.069824,6242.700195,5.236740e+09,5.739030e+09
6411,6227.419922,6279.350098,6229.979980,6225.520020,6263.259766,6262.069824,6242.700195,6269.160156,5.739030e+09,4.813340e+09
6412,6279.350098,6229.979980,6225.520020,6263.259766,6280.459961,6242.700195,6269.160156,6290.220215,4.813340e+09,5.367350e+09

In [ ]:
columns = ['High', 'Low', 'Close', 'Volume', 'logReturns']
train_window = 3 
target = 'Close'
target_row = df[target].iloc[train_window:].values

full_windowed = np.array([])
for col in columns:
    df_col = df[col]
    windowed_col = np.array([df_col.iloc[i-train_window:i].values for i in range(train_window, len(df_col))])
    if len(full_windowed) == 0:
        full_windowed = windowed_col
    else:
        full_windowed = np.concatenate((full_windowed, windowed_col), axis=1)
column_names = [f"{col.lower()}-{i}" for col in columns for i in range(train_window, 0, -1) ]
windowed_df= pd.DataFrame(full_windowed, columns=column_names)
windowed_df

(6415, 3)
(6415, 3)
(6415, 3)
(6415, 3)
(6415, 3)

,high-3,high-2,high-1,low-3,low-2,low-1,close-3,close-2,close-1,volume-3,volume-2,volume-1,logreturns-3,logreturns-2,logreturns-1
0,1455.219971,1413.270020,1411.900024,1397.430054,1377.680054,1392.099976,1399.420044,1402.109985,1403.449951,1.009000e+09,1.085500e+09,1.092300e+09,-0.039099,0.001920,0.000955
1,1413.270020,1411.900024,1441.469971,1377.680054,1392.099976,1400.729980,1402.109985,1403.449951,1441.469971,1.085500e+09,1.092300e+09,1.225200e+09,0.001920,0.000955,0.026730
2,1411.900024,1441.469971,1464.359985,1392.099976,1400.729980,1441.469971,1403.449951,1441.469971,1457.599976,1.092300e+09,1.225200e+09,1.064800e+09,0.000955,0.026730,0.011128
3,1441.469971,1464.359985,1458.660034,1400.729980,1441.469971,1434.420044,1441.469971,1457.599976,1438.560059,1.225200e+09,1.064800e+09,1.014000e+09,0.026730,0.011128,-0.013149
4,1464.359985,1458.660034,1442.599976,1441.469971,1434.420044,1427.079956,1457.599976,1438.560059,1432.250000,1.064800e+09,1.014000e+09,9.746000e+08,0.011128,-0.013149,-0.004396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6410,6210.779785,6227.600098,6284.649902,6177.970215,6188.290039,6246.459961,6198.009766,6227.419922,6279.350098,6.275310e+09,5.645710e+09,3.378110e+09,-0.001119,0.004734,0.008304
6411,6227.600098,6284.649902,6262.069824,6188.290039,6246.459961,6201.000000,6227.419922,6279.350098,6229.979980,5.645710e+09,3.378110e+09,5.236740e+09,0.004734,0.008304,-0.007893
6412,6284.649902,6262.069824,6242.700195,6246.459961,6201.000000,6217.750000,6279.350098,6229.979980,6225.520020,3.378110e+09,5.236740e+09,5.739030e+09,0.008304,-0.007893,-0.000716
6413,6262.069824,6242.700195,6269.160156,6201.000000,6217.750000,6231.430176,6229.979980,6225.520020,6263.259766,5.236740e+09,5.739030e+09,4.813340e+09,-0.007893,-0.000716,0.006044
6414,6242.700195,6269.160156,6290.220215,6217.750000,6231.430176,6251.439941,6225.520020,6263.259766,6280.459961,5.739030e+09,4.813340e+09,5.367350e+09,-0.000716,0.006044,0.002742

In [5]:
columns = ['High', 'Low', 'Close', 'Volume', 'logReturns']
target = 'Close'
windowed_dfs(df, columns, target, train_window=10)

(          high-10       high-9       high-8       high-7       high-6  \
 0     1455.219971  1413.270020  1411.900024  1441.469971  1464.359985
 1     1413.270020  1411.900024  1441.469971  1464.359985  1458.660034
 2     1411.900024  1441.469971  1464.359985  1458.660034  1442.599976
 3     1441.469971  1464.359985  1458.660034  1442.599976  1454.199951
 4     1464.359985  1458.660034  1442.599976  1454.199951  1473.000000
 ...           ...          ...          ...          ...          ...
 6403  6018.200195  6028.770020  6101.759766  6108.509766  6146.520020
 6404  6028.770020  6101.759766  6108.509766  6146.520020  6187.680176
 6405  6101.759766  6108.509766  6146.520020  6187.680176  6215.080078
 6406  6108.509766  6146.520020  6187.680176  6215.080078  6210.779785
 6407  6146.520020  6187.680176  6215.080078  6210.779785  6227.600098

            high-5       high-4       high-3       high-2       high-1  ...  \
 0     1458.660034  1442.599976  1454.199951  1473.000000  1465.150024  ...
 1     1442.599976  1454.199951  1473.000000  1465.150024  1461.390015  ...
 2     1454.199951  1473.000000  1465.150024  1461.390015  1465.709961  ...
 3     1473.000000  1465.150024  1461.390015  1465.709961  1453.180054  ...
 4     1465.150024  1461.390015  1465.709961  1453.180054  1454.089966  ...
 ...           ...          ...          ...          ...          ...  ...
 6403  6187.680176  6215.080078  6210.779785  6227.600098  6284.649902  ...
 6404  6215.080078  6210.779785  6227.600098  6284.649902  6262.069824  ...
 6405  6210.779785  6227.600098  6284.649902  6262.069824  6242.700195  ...
 6406  6227.600098  6284.649902  6262.069824  6242.700195  6269.160156  ...
 6407  6284.649902  6262.069824  6242.700195  6269.160156  6290.220215  ...

       logreturns-10  logreturns-9  logreturns-8  logreturns-7  logreturns-6  \
 0         -0.039099      0.001920      0.000955      0.026730      0.011128
 1          0.001920      0.000955      0.026730      0.011128     -0.013149
 2          0.000955      0.026730      0.011128     -0.013149     -0.004396
 3          0.026730      0.011128     -0.013149     -0.004396      0.012096
 4          0.011128     -0.013149     -0.004396      0.012096      0.010615
 ...             ...           ...           ...           ...           ...
 6403      -0.002181      0.009561      0.011060     -0.000003      0.007988
 6404       0.009561      0.011060     -0.000003      0.007988      0.005205
 6405       0.011060     -0.000003      0.007988      0.005205      0.005151
 6406      -0.000003      0.007988      0.005205      0.005151     -0.001119
 6407       0.007988      0.005205      0.005151     -0.001119      0.004734

       logreturns-5  logreturns-4  logreturns-3  logreturns-2  logreturns-1
 0        -0.013149     -0.004396      0.012096      0.010615     -0.006856
 1        -0.004396      0.012096      0.010615     -0.006856      0.000522
 2         0.012096      0.010615     -0.006856      0.000522     -0.007121
 3         0.010615     -0.006856      0.000522     -0.007121     -0.002917
 4        -0.006856      0.000522     -0.007121     -0.002917     -0.028023
 ...            ...           ...           ...           ...           ...
 6403      0.005205      0.005151     -0.001119      0.004734      0.008304
 6404      0.005151     -0.001119      0.004734      0.008304     -0.007893
 6405     -0.001119      0.004734      0.008304     -0.007893     -0.000716
 6406      0.004734      0.008304     -0.007893     -0.000716      0.006044
 6407      0.008304     -0.007893     -0.000716      0.006044      0.002742

 [6408 rows x 50 columns],
 array([1455.90002441, 1445.56994629, 1441.35998535, ..., 6263.25976562,
        6280.45996094, 6259.75      ], shape=(6408,)))